version: '3.7'
services:
    mongo:
        image: "mongo"
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"

    web:
        build: .
        image: recruitlete
        ports:
            - "3000:3000"
        depends_on: 
            - mongo

