version: '3.7'
services:
    mongo:
        image: "mongo"
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"

    web:
        build: .
        # command: "node server.js"
        image: recruitlete
        ports:
            - "5000:5000"
        depends_on: 
            - mongo

